#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use tars\TarsGenerateCommand;
use tars\TarsGenerator;

if (version_compare('7.1.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of PHPUnit is supported on PHP 7.1 and forward.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

$autoloadFile = null;
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        $autoloadFile = $file;
        break;
    }
}

if ($autoloadFile === null) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}
require $autoloadFile;

$app = new Application("tars-gen", TarsGenerator::VERSION);
$app->add(new TarsGenerateCommand());
$app->setDefaultCommand("tars:generate", true);
$app->run();